
// FUNÇÃO 

// função soma
function soma (op1 , op2){
    var resultadoC = op1 + op2;
    return resultadoC;
}

var resultadoSoma = soma (1,2);
console.log(resultadoSoma);

var outroResultado = soma (50,100);
console.log(outroResultado);



// função subtração
function sub (ope1 , ope2){
    var resultadoSub = ope1 - ope2;
    return resultadoSub;
}

var resultadoSubtracao = sub (20,10);
console.log (resultadoSubtracao);


//função para strings

function helloWord (nome){
    console.log('Bem vindo a linguagem Java Script, ' + nome + '!');
}

helloWord ('Nicolle');

