
// Condicional IF-ELSE
console.log (' IF - ELSE')
var nome = 'nicolle';

if (nome === 'nicolle'){
    console.log('nome correto!')
} else {
    console.log ('nome incorreto!')
}


// Condicional mais complexa com IF- ELSE IF - ELSE
console.log (' IF - ELSE IF - ELSE')
var senha = '123456';

if (senha == '123456'){
    console.log('Sua senha esta correta!');
} else if (senha == '654321'){
    console.log('pode ser essa senha tambem!');
} else {
    console.log ('senha nao confere!')
}