
// Operadores Matematicos
console.log (' OPERADORES MATEMATICIOS')
var valor1 = 10;
var valor2 = 5;

var resultado = valor1 + valor2 ; // soma
console.log('A soma é :  ' + resultado);

var resultado = valor1 * valor2 ; // multiplicação
console.log('O produto é :  ' + resultado);

var resultado = valor1 / valor2 ; // divisão
console.log('O quociente é :  ' + resultado);

var resultado = valor1 - valor2 ; // subtração
console.log('O resto é :  ' + resultado);















