
// SWITCH CASE BREAK DEFAULT
console.log (' SWITCH CASE ')
var nome = 'nicolle'

switch (nome) { 
    case 'nicolle':  //if
    console.log (' pode ser !')
    break;
    case 'gianinni': // else if
    console.log (' pode ser também!')
    break;
    case 'nicolle gianinni': // else if
    console.log (' nome completo. pode ser também!')
    break;
    default: //else
    console.log (' incorreto!')
    break;
}